### ISSUE TITLE
minor and major collisions are not defined in the rulebook

### ISSUE THREAD

**Issue by frederikhegger** [robocup-at-work/rulebook#15]
The distinction between minor and major collisions actually does not exist in the rulebook (just controlled collision (no penalty) and collision (normal collision penalty).

**Comment by asadnorouzi** [comment]
@frederikhegger Let’s bring in the exact quotes from the rulebook here and rewrite them for better clarity. Will you do it?

**Comment by frederikhegger** [comment]
Unfortunately, I do not work anymore for the university and also not anymore in the domain of robotics. Sorry

**Comment by steup** [comment]
I agree that we need to rework the whole collision penalty system. For starters we should specify different types of collisions and add the penalties to them. I propose the following collision types:

- Collision with static elements of arena
- Collision with dynamic elements of arena
- Robot Body Collision with workstation
- Robot Manipulator Collision with manipulation zone
- Robot Manipulator Collision with Round Table stopping it
- Robot Manipulator Collision with PPT Cavity surface
- Robot Manipulator Collision with Shelf

Some of them may be redundant regarding the penalties, but for clarification I think it is good to specify them explicitly. Additionally, it allows us to loosen or tighten the rules for special collision in the future.
