### ISSUE TITLE
Do not allow to place objects on top of other objects

### ISSUE THREAD

**Issue by frederikhegger** [robocup-at-work/rulebook#16]
Except for e.g. an assembly or placing into a container

**Comment by asadnorouzi** [comment]
agreed!

**Comment by steup** [comment]
Is only a viable additional challenge if we enforce placement to be done within the manipulation zone of the workstation. Increases difficulty for placing tasks especially on crowded workstations. Also adds a penalty for incorrect container placement.

**Comment by SebastianZug** [comment]
That's not a problem from my perspective. The objects must be located within the manipulation zone / container. If we start to analyze its position (close to the wall, on top of another object, etc.), we open up Pandora's box.
