### ISSUE TITLE
Make use of the dynamic inventory of the CFH (refbox)

### ISSUE THREAD

**Issue by frederikhegger** [robocup-at-work/rulebook#18]

**Comment by asadnorouzi** [comment]
@frederikhegger Please elaborate!

**Comment by frederikhegger** [comment]
I do not remember anymore, what this was about. But maybe @svenschneider does have an idea.

**Comment by svenschneider** [comment]
Too long ago, no more memories on that one. Sorry.

**Comment by steup** [comment]
Lets close this one to focus on the relevant aspects
