### ISSUE TITLE
Use object instance IDs for 2017

### ISSUE THREAD

**Issue by frederikhegger** [robocup-at-work/rulebook#2]
Before we had no instance_ids therefore even though we configured e.g:

F20_20_B from S1 -> S3
F20_20_B from S2 -> S4

It was possible to transport F20_20_B from S1->S4. Since only the initial and the final scenario where compared. This resulted in a problem when using areas both as source and destination, since we could have configured a task where an object would not need to be moved: e.g:

F20_20_B from S1 -> S2
F20_20_B from S2 -> S4

The correct goal scenario would be reaches with only one transaction, resulting in missing of points for pickup and for placing the objects. The rules do not clearly state how to do this, the current "clips-rules" split source and destination.

**Comment by asadnorouzi** [comment]
Are we still discussing it for 2020?

**Comment by steup** [comment]
That one is tricky, because the internal rules allows the specification, but the visualization does not show it. It would need changes to visualization. The new RefBox fixes the problem, when it is ready.

**Comment by asadnorouzi** [comment]
OK then, let’s close it for now.
