### ISSUE TITLE
Define ideal networking setup for teams and robots

### ISSUE THREAD

**Issue by deebuls** [robocup-at-work/rulebook#28]
The league should define an ideal networking solution for teams, for smooth conduct of competition.

RoboCup wifi is always been problematic, but still we need wireless Communication for status and control of the robot.

Hence the league should define ideal hardware, protocols, channels and networking setup for handling the challenges

**Comment by asadnorouzi** [comment]
The hardware, setup, and infrastructure is provided by the LOC. There’s no way for us to have a complete control over it. We could indicate our requirement and hope that it would properly prepared by the LOC!!
