### ISSUE TITLE
Making 2 testbeds for Basic and advanced tests

### ISSUE THREAD

**Issue by deebuls** [robocup-at-work/rulebook#31]
We can have 2 separate testbeds:
1. Basic tests(BMT, PPT, RRT, Challenges)
2. Other test (BTT, Finals)

Requirements:
1. Testbed needs to be designed to accomodate this requirement
2. Schedule has to adjust these changes.

Advantages:
1. Test slots of teams and basic tests can be run parallely
2. Multiple runs can be run for basic test and challenges

**Comment by asadnorouzi** [comment]
This is very much relies on how much space we have available each year. Therefore, I do not think we can add it to the rules permanently. If we do this, it would mean that we are requiring a larger field size which is not really a favorable request. I do like the idea, but given that we have a structured plan for its implementation to avoid unnecessary arguments during the competition. Let’s see what others have to say about this.

**Comment by steup** [comment]
If we have two comparable complete arenas, I am in favor of assigning teams to arenas and let them do their tests and competitions in their arena. For competition runs I would not let multiple runs be done in parallel, but we can schedule the teams alternating between the arenas to increase the time for the referees to prepare the arena. Using that we may be able to reduce the down-time between competition runs.

**Comment by deebuls** [comment]
To summarize:
@asadnorouzi  has pointed out we cannot get bigger areas from organizer so idea has to be implemented in the same size 
@steup  comparable complete arenas, assigning teams to arena, mentioned no parallel runs.

@deebuls 2 arena (dividing our current big arena to 2, small and big) based on the tests(basic test advanced test), no parallel runs, run multiple basic test and challenges in smaller arena, in final combine both arena.

@asadnorouzi @SebastianZug  @steup We can do 1 more round of discussion then will put these ideas to vote.
