### ISSUE TITLE
Fix / Change the RefBox!

### ISSUE THREAD

**Issue by asadnorouzi** [robocup-at-work/rulebook#32]
The current RefBox doesn’t function properly. Who will take lead to have it changed or fixed? Any volunteers?

**Comment by SebastianZug** [comment]
There are some activities in Magdeburg in this direction ... probably @steup can give some comments?

**Comment by steup** [comment]
We are currently working on a RefBox based natively on ROS. The RefBox will use Multi-Master to decouple the robots from the RefBox and allows the transmission of tasks to individual robots. The Visualization is based on RViz and a FeedBack channel is included, to allows the robots to send their view of the world back for visualization purposes. If necessary we can include additional communication links using a plugin communication system.

We aim to have a working prototype running for the German Open 2020.

**Comment by asadnorouzi** [comment]
@steup Thank you Christoph! This sounds awesome :) If prototype is to be released by German Open 2020, it would mean that we still couldn’t have it released in time for all teams to integrate before RoboCup 2020. Therefore, we still need someone to fix the current RefBox for RoboCup 2020. Do you have any suggestion?

**Comment by abhishekpadalkar** [comment]
@steup It the repository of this new RefBox public yet?? Please specify the link so that we can also contribute.

**Comment by steup** [comment]
We will upload the refbox Prototype when there is a minimal working version. We are currently working on it. I hope it will be done by the end of February.

**Comment by DharminB** [comment]
Maybe we can try the interface ([link](https://docs.google.com/document/d/1vba1dIjxMPEHUaE4sGCUeb1DqVaoS0PqidXd55esFp8/edit?usp=sharing) section 5) which was used for sciroc 2019. We have the [client](https://github.com/b-it-bots/sciroc_datahub_client) ready. I can work on server side if you like. 

Communication happens via api calls (no ROS needed).

**Comment by steup** [comment]
Our current approach uses a ROS-based System with communication plugins for multiple other interfaces. Therefore no client is necessary for the current teams, besides a parsing of ROS messages. For teams not using ROS other interfaces like the old RefBox interface will be provided. Therefore no one needs to change anything, at least not this year. Currently communication is implemented and task generation is nearly done. Final step to prototype is integration and testing. Afterwards we gladly accept communication plugins for all your needs :-)

**Comment by asadnorouzi** [comment]
As I have mentioned previously, we can’t use the RefBox that @steup and his team are developing for RoboCup 2020. Teams will need to have adequate time to change their RefBox module. The initial version of the new RefBox will be tested during the GermanOpen. So, absolutely not enough time for others to use it for RoboCup 2020. I suggest we introduce the new RefBox to all teams during RoboCup 2020. This means that we would still need someone to make the current version work for 2020. @SebastianZug Do you know someone who can help with the current version and make it stable and up to date based on the current rules?
