### ISSUE TITLE
Propose a new challenge

### ISSUE THREAD

**Issue by deebuls** [robocup-at-work/rulebook#33]
Please provide a challenge for robocup@work 2020 challenges. The benchmark categories we are interested are:

1. Navigation
2. Manipulation
3. Perception
4. Planning
    
The general guidelines for the challenges are:
1. Should be a combination of 2 research categories
2. Should be interesting for teams to participate
3. Should be a doable task with robot hardware
4. Should be interesting to audience, consider gamification of challenge
5. Should be benchmark-able i.e. doesn't need a human judge to say correct or wrong
6. Should be different from other robotics competition

Please use the template below for submitting a request:
1. Name
2. Short description
3. Benchmark categories it will include
4. How is it different from other test
5. How will it be interesting to audience
6. Scoring strategy
7. Easiness for teams to participate

**Comment by deebuls** [comment]
Example The following is from @SebastianZug 


    Name : Pick from a drawer
    Short description : Open the drawer, look for an object, pick it, and close the drawer.
    Benchmark categories it will include : Perception and Manipulation 
    How is it different from other test : First test with changing state of environment.
    How will it be interesting to audience : the complexity of an in-drawer-grasping-operation is more intuitive
    Scoring strategy :  200 for opening drawer , 100 for each object grasped 
    Easiness : we should permit individual settings and define just some basic dimensions

**Comment by abhishekpadalkar** [comment]
```
Name: Organize the tool-box
Short description: Collect the tools lying all over the workstations at one workstation. It is not a new challenge but can be an addition to existing challenge e.g. BMT 2. The number and locations of tools will not be given to the robot as an order, instead, the robot has to dynamically detect the tools and transport them to the workstation defined as tool-box. 
Benchmark categories it will include: Dynamic task planning, perception, grasping. 
How is it different from other tests: Partially unknown order.
How will it be interesting to the audience : Tidying up the workplace simultaneously while working can be very interesting and intuitive.
Scoring strategy:  Same as any other object in BMT 2. Tools can be standardized by specifying a brand.  
Easiness: Initially we can start with screwdrivers.   

```

**Comment by SebastianZug** [comment]
The proposal of @abhishek098 resumes the Rockin concept. The robot collects all parts required for a certain assembly task at one workstation (and starts the manufacturing process). Can we transfer this long term vision in a number of challenges for the next years, that build upon one another. In this way we are able to address a general strategy for our challenges :-)

**Comment by abhishekpadalkar** [comment]
@SebastianZug next year means 2021 or 2020? It is a bit different than the Rockin challenge as collecting tools is a secondary goal and location will be unknown (But still will be on the same workstations that robot is supposed to perceive). BMT tasks already realize the Rockin concept. Collecting previously unknown objects will add crisp to the conventional pick and place task in BMT2. I think we can introduce this challenge successfully with minimum changes in the rulebook as well as the arena. That's why it is very much possible to introduce it in german open.

**Comment by DharminB** [comment]
```
Name: Place in unknown environment
Short description: Place an object on a workstation by traversing an unknown environment/maze. (obj is on robot platform and square has aruco markers at corners) 
Benchmark categories it includes: Navigation and perception
How is it different from other tests: No other test has unknown/unmapped environment
How will it be interesting to audience: The robot missing an obvious route might be funny and interesting
Scoring strategy:  Max time is 500 seconds. Team gets points equal to the amount of seconds left after placing.
Easiness: Smaller area with just 2 workstation
```

**Comment by SebastianZug** [comment]
Ok, I added the description of the drawer challenge in our document. Please take a view to the motivation. I would like to define a medium-term strategy for our league represented by challenges with a specific focus. Currently, I am convinced that it makes sense to include the "Cluttered Pick Test" again. It meets a strategy aiming at manipulation and perception perfectly. 

What do you think?
