### ISSUE TITLE
RoboCup@Work CFP for RoboCup 2020

### ISSUE THREAD

**Issue by asadnorouzi** [robocup-at-work/rulebook#35]
I am planning to send the CFP for RoboCup 2020 and start the pre-registration before the end of January. Please review the following announcement and let me know if you would like to change any part of the announcement:

<—
Apologies for duplicate messages
------------------------------------------------------------------------------------  
Call for Applications for Participation
RoboCup 2020 - RoboCup at Work
https://2019.robocup.org
Bordeaux, France
Tuesday 23rd through Monday 29th June 2020
RoboCup at Work: Competing for the Factory of the Future
------------------------------------------------------------------------------------  

RoboCup at Work is a league and competition in RoboCup that targets the use of robots in work-related, industrial scenarios.

It aims to foster research and development that enables the use of innovative mobile robots equipped with advanced manipulators for current and future industrial applications, where robots cooperate with human workers for complex tasks ranging from manufacturing, automation, and parts handling up to general logistics.

The RoboCup at Work league is characterized by an industrial appealing environment composed of industrial objects such as screws and nuts, shelves, containers, platforms of various sizes and networked automation devices such as conveyor belts, drilling machines, and others.

The actual competition tasks to be performed in the environment are defined in a set of so-called tests. Each test addresses various mobile manipulation capabilities such as grasping, transportation, precision placement, and visual servoing.

The full rules of RoboCup at Work as well as further technical details are posted on the RoboCup at Work website.

Participation in the Competition
-------------------------------------------
All teams that intend to participate in the competition have to perform the following steps:

1) Submission of qualification material, including a Team Description Paper and possibly additional material like videos or drawings

2) Final registration (qualified teams only)

Qualification
-------------------
The qualification process serves a dual purpose: It should allow the Technical Committee to assess the safety of the robots a team intends to bring to a competition, and it should allow to rank teams according to a set of evaluation criteria in order to select the most promising teams for a competition, if not all interested teams can be permitted. The TC will select the qualified teams according to the qualification material provided by the teams.

The evaluation criteria will include:
- Team description paper
- Relevant scientific contribution/publications
- The professional quality of robot and software
- Novelty of approach
- Relevance to industry
- Performance in previous competitions
- Contribution to RoboCup at Work league, e.g. by
-- Organization of events
-- Provision and sharing of knowledge
- Team web site

Team Description Paper
-----------------------------------
The Team Description Paper (TDP) is a central element of the qualification process and has to be provided by each team as part of the qualification process. The TDP should at least contain the following information in the author/title section of the paper:
- Name of the team (title)
- Team members (authors), including the team leader
- Link to the team web site
- Contact information
- The body of the TDP should contain information on the following:
-- focus of research/research interest
-- description of the hardware, including an image of the robot(s)
-- description of the software, esp. the functional and software architectures
-- innovative technology (if any)
-- reusability of the system or parts thereof
-- applicability and relevance to industrial tasks
-- usage of components (software or hardware) developed by other RoboCup at Work teams

The team description paper should cover in detail the technical and scientific approach, while the team web site should be designed for a broader audience. Both the web site and the TDP have to be written in English.

Submission and Evaluation
---------------------------------------
All applications with the qualification material must be submitted by February 14th, 2020 through the following online form:
https://forms.gle/1ZiXQzU7nxJfBVvR8

Qualified teams will be tentatively announced by March 6th, 2020.

Best regards,
The RoboCup at Work Technical and Organizing Committees
—>

**Comment by SebastianZug** [comment]
No comments from my side! For the next year we have to prepare a latex document to ensure homogeneous TDPs.

**Comment by asadnorouzi** [comment]
@SebastianZug Would you like to use the RoboCup Symposium template? Last year, they used this template: https://www.overleaf.com/latex/templates/springer-lecture-notes-in-computer-science/kzwwpvhwnvfj#.WtR5Hy5ua71

**Comment by SebastianZug** [comment]
Yes, nice idea. Next year we add an obligatory structure for the document.
