### ISSUE TITLE
Define Difficulty Levels

### ISSUE THREAD

**Issue by steup** [robocup-at-work/rulebook#39]
The current setup of the league makes it hard for new teams to enter the competition. It may be benficial to define difficulty levels, which disable parts of the challenges of the competition to make it more achievable for new teams with reasonable effort.

I suggest to handle the difficulty levels as a trade-off between challenges encountered in the arena on run-time and points awarded per task (move, pick and place)

The easiest way to modify the challenges of each run without the need to modify the run by the referees is to increase or decrease the amount of information handed to the robot of each team by the RefBox. 

I envision the following difficulty levels for example:

- Easy:
 - Move points are modified by -75%
 - Pick and Place are modified by -75%
 - The position, rotation and orientation of all objects and decoys in the arena are delivered to the robot
 - Obstacles in the arena are described by a bounding box
 - Arbitrary surfaces type is announced per workstation
 - Barrier tapes are not counted

- Medium:
 - Move points are modified by -50%
 - Pick and Place are modified by -50%
 - The position and orientation of all objects and obstacles in the arena are delivered to the robot
 - The existence of arbitrary surfaces on each table is announced, the type not
 - Barrier tapes are counted

Hard (default):
 - Move points are modified by 0%
 - Pick and Place are modified by 0%
 - No additional information regarding object location and placement is given besides the workstation
 - No additional information regarding obstacles
 - No information on arbitrary surfaces
 - Barrier tapes are counted

Nightmare (realistic workshop):
  - Move points are modified  by -100%
  - Place points are modified by 0%
  - Pick points are modified by +300%
  - No information is given regarding the location of any object in the arena (Objects, Decoy) besides the target workstation of objects
  - No additional information regarding obstacles 
  - Barrier tapes are counted doubled
 
Implementation:

Each robot sends the requested difficulty level to the RefBox as part of the registration process.
The refbox adapts the information content based on the requested difficulty level on sending out the task

Necessary change to the RefBox client of each team:

- Set the difficulty level
- Switch to team specific topic for task delivery

**Comment by marcomasa** [comment]
I'd rather help teams to get to some sort of "standard" level, which is what all successul teams of the past years should have achieved already. So once again, some kind of tutorial pages which new teams can use to gather ideas from our experience.

I don't like the idea of the difficulty levels. Movement points are already quite low, and the obstacles are relatively easy to avoid (physical). We could discuss the barriertape aspect, as this is indeed a problem. But i also think that, in addition to physical surroundings observation, we should encourage teams to also implement visual coverage.

**Comment by leanderb** [comment]
closed, because the issue is very old and the rulebook have been rewritten in the meantime
