### ISSUE TITLE
Define Scope of Definition of Arena Elements

### ISSUE THREAD

**Issue by steup** [robocup-at-work/rulebook#40]
Currently the Arena Elements (Workstations, Walls, Objects etc.) are only defined very sparsely. For the teams to be able to adapt their new robots to the arena encountered in the competition more specification is necessary.

We should define the amount of limitations we want to set to the Arena Elements regarding size, weight and materials.

Additionally there should be construction or acquisition instructions on how to get these Arena Elements in reasonable time and effort (time and money-wise) to build local training arenas.

**Comment by marcomasa** [comment]
Arena rules will be defined until wednesday (first draft).

As mentioned in #41 , we should do some tutorial pages for the league for new teams. This also includes arena building advice.

**Comment by leanderb** [comment]
closed, because the issue is very old and the rulebook have been rewritten in the meantime
