### ISSUE TITLE
Define a Simulation Challenge for Virtual RoboCup 2021

### ISSUE THREAD

**Issue by steup** [robocup-at-work/rulebook#41]
Currently the league has no simulator readily available. In the last meeting multiple options were discussed. However, a comparision of these regarding the requirements of the league is difficult without looking at them.

Consequently, a n open simulation challenge may provide some inside into the capabilities and trade-offs of the different simulators out there.
I suggest to define an open simulation challenge with the following content:

- The simulator needs to be freely available and needs to be usable by teams free of charge.
- The team needs to supply the simulation backend including physics and hardware simulation mechanisms
- The team does NOT need to provide the code executing the task
- The virtual environment needs to consists of a team specific model of their own robot and a replication of the arena of the Virtual RoboCup 2021 based on the models from the official repository
- The task executed  needs to be generated by the refbox
- The team shows their simulation in alive session using a communication tool like (zoom, discord, bigbluebutton etc.)

The team is graded regarding the following categories:

- Difficulty of the task executed
- Precision of the execution
- Performance of the simulator (smoothness, frame rate (live view), simulation speed (unattended mode))
- Realism of the executed behaviours

**Comment by marcomasa** [comment]
I haven't seen a realistic modelling for object manipulation (physics and graphics) which can run on a "normal" pc yet..
So these tasks would mainly include navigation. As a lot of teams use custom platforms (no youbot anymore), individual advantages of construction (controllers, precision, speed) may fall off hard. As our league depends on new teams, bringing in new ideas and/or sharing construction plans, i would suggest to focus on something else.

We should think about "Tutorial" pages, where new teams can get ideas of stuff we solved in the past robocups. This would help them cross starting hurdles and bring our league to new fields of research.

**Comment by leanderb** [comment]
closed, because the issue is very old and the rulebook have been rewritten in the meantime
