### ISSUE TITLE
Remove Rockin objects and add new objects available in all countries or 3D print parts

### ISSUE THREAD

**Issue by deebuls** [robocup-at-work/rulebook#45]
Since rockin objects are no more available, we should remove them and add some common objects available in the hardware shop. 

I very much like the ![tless dataset](http://cmp.felk.cvut.cz/t-less/) but when I contacted them from where they bought it; it was only available in Coratia.

Another good idea can be 3D printed parts, like a simple useful dailty stiff https://all3dp.com/1/small-quick-easy-fun-things-to-3d-print-when-bored/

A puzzle which needs to be assembled by robot can also be interesting.

**Comment by slyandsmart** [comment]
New Objects included in the new ruelbook 2022, as well as 3D printig procedure for RockinObjects (same color for all printed objects).
