### ISSUE TITLE
Clarify moment of barrier tape deduction

### ISSUE THREAD

**Issue by leanderb** [robocup-at-work/rulebook#49]
from Discord rule-book-discussion-2022 channel:
4. Scoring in case of deduction in percentage (e.g. tape collision): It is probably meant to be a deduction of the total points at the end, but it could also be e.g. 5% of the points gained until the time of the tape collision

**Comment by marcomasa** [comment]
Requires much more overhead for refs. I would stick with the deduction of the total points. 
We could clarify that in the RB however.

**Comment by steup** [comment]
I suggest we use percentage points to indicate deduction and increases to ease computation and prevent these discussions.

**Comment by leanderb** [comment]
- deduction at the end
TODO TC: clarify in rulebook

**Comment by leanderb** [comment]
"of the final points are deducted" already in the rulebook
