### ISSUE TITLE
Clarify manipulation zone size

### ISSUE THREAD

**Issue by leanderb** [robocup-at-work/rulebook#50]
from Discord rule-book-discussion-2022 channel:
5. Conflict between "max. Manipulation zone is 20 cm (p.33) and image on page 34, where the manipulation zone + 2cm at the border of the workstation combined are 20cm. -> 2cm border and 18cm manipulation zone  OR 2cm border and 20cm manipulation zone = 22cm into the table

**Comment by leanderb** [comment]
- manipulation zone is 20cm in depth and 2cm between table border and beginning of manipulation zone
TODO TC: just clarify

**Comment by slyandsmart** [comment]
Defined in new rulebook2023 with new shematic drawing of one whole table (including 2 WS).
