### ISSUE TITLE
Allowed height above container  

### ISSUE THREAD

**Issue by leanderb** [robocup-at-work/rulebook#51]
from Discord rule-book-discussion-2022 channel:
6. Define correct placement for containers: 5cm from manipulation zone or 5cm from container edge
Suggestion for now: 10cm from manipulation zone for containers

**Comment by leanderb** [comment]
from Discord rule-book-discussion-2022 channel:
8. Define scoring / penalty for the case that an object which shall be placed in a container is dropped more than 5cm above the manipulation zone (See point 6) but misses the container (object loss vs scoring to motivate the teams to try container tasks: reduce the risk)

**Comment by leanderb** [comment]
- manipulation zone height for containers is the same as for all other placement tasks
- the robot manipulator fingers had to move inside the container below 5 cm
- if the container is missed, the team is awarded with points minus the place deduction
- correct container placement: the object touches the bottom of the container
- object loss still possible: when the object lays on top of the container
TODO TC: implement in rulebook

**Comment by slyandsmart** [comment]
Included in Rulebook2023 in container placement examples.
