### ISSUE TITLE
Reward placement on RTT

### ISSUE THREAD

**Issue by leanderb** [robocup-at-work/rulebook#52]
from Discord rule-book-discussion-2022 channel:
9. If placement on arbitrary surface is rewarded with additional points, so should placement on the rtt, because it is even more difficult to determine an object-free area over there

**Comment by steup** [comment]
I think, this is not necessary as the deduction of points is not 100% in case of errors like colliding with another object. Consequently, points will still be awarded, but less.

**Comment by leanderb** [comment]
RTT not part of main tests anymore

RTT technical challenge is grasping only
