### ISSUE TITLE
Clarify call of major collision 

### ISSUE THREAD

**Issue by leanderb** [robocup-at-work/rulebook#53]
from Discord rule-book-discussion-2022 channel:
10. How is a major detected, should the referees shout?

**Comment by steup** [comment]
This point is essential. It also needs to be clarified how to handle major calls of bystanders. And how fast the refs need to agree, or if a simple shout is enough. This of course leaves room for manipulation. Especially, major calls from bystanders may impact the opinion of inexperienced refs, jeopardizing the independent and fair assessment of the runs.

**Comment by leanderb** [comment]
- if 4 refs or more (+ 1 head ref) are available (determined by the number of teams participating), only referees (refs + head ref) are allowed to call a major collision
- if less than 4 refs (+ 1 head ref) are available, referees and TC members are allowed to call major collisions 
- nobody else is allowed to call a major collision
- pay special attention to this topic in the referee briefing
- it is not allowed for anybody to enter the referee zone around the arena except the referees and TC members 
- if a team calls stop before an occurred major collision is declared, the major collision is handled as never happened
