### ISSUE TITLE
PPT with new objects

### ISSUE THREAD

**Issue by leanderb** [robocup-at-work/rulebook#54]
from Discord rule-book-discussion-2022 channel:
11. PPT with the new objects?

**Comment by steup** [comment]
I think this would be a nice addition to the old PP task. Maybe with a fixed ratio of 2 old objects and 1 new object.

**Comment by leanderb** [comment]
testing the new objects in the normal placement and container placement tasks first is preferred

discuss in the next year, whether the new objects will be used for PPT

**Comment by leanderb** [comment]
already in the rulebook "For the Precision Placement Table only the RoboCup@Work Object Set will be used."
