### ISSUE TITLE
Major collision penalty is too harsh

### ISSUE THREAD

**Issue by leanderb** [robocup-at-work/rulebook#57]
problem description:
a major collision resets the points to 0 and restarts the run; the new points are multiplied
with 0.75; the idea is, that a major collision must not happen, because things might be
damaged, or even worse, persons could be injured; the problem: the later a major collision
occurs, the harsher the penalty, because the time becomes smaller and smaller; furthermore
teams with very good manipulation skills, but bad navigation gets most the time only a few
points; new teams had to concentrate on the navigation, because manipulation is useless
without reliable navigation, but you only get a few points (service area reached points)

**Comment by marcomasa** [comment]
We could change the system to:
- a collision does not reset your score, but applies a harsh penalty multiplier (e.g. 0.4) to collected points of that run
- team has the option to restart the run with less time, but with the regular penalty (e.g. 0.8) 

New teams can still restart their run, but the experienced teams can also keep their (reduced) score if they would have no more time to perform tasks after a restart.

We could still talk about the factors, but i think this balances this rule a bit.

**Comment by steup** [comment]
The major issue with major collisions is the time factor. A late major collision is much more severe than an early one.

Maybe we should introduce a time-varying penalty factor for the restart depending on the amount of time left.

We could also go with a large fixed point deduction, but this may leave a lot of beginner teams with 0 points.

**Comment by Mathemalsky** [comment]
How about setting the harsh multiplier to the proportion of time elapsed, times e. g. 0.75?

**Comment by leanderb** [comment]
TC meeting:
when a major collision occurs:
- the team can decide whether they stop the run and get 50% of the already reached points or to restart
- the normal restart rules apply in the latter case
- when a 2nd major collision occurs, the run is stopped and the team get 50% of the points reached in the second try
