### ISSUE TITLE
Tactical call of restart

### ISSUE THREAD

**Issue by leanderb** [robocup-at-work/rulebook#58]
problem description:
tactical call of a restart: to prevent the major collision penalty, teams try to call stop or
restart when it is likely (sometimes only to the team) that a major collision happens; a work
around used by the referees is, that the robot had to continue operation 5 seconds after the
restart was called (this is not defined in the rulebook)

**Comment by marcomasa** [comment]
I think it should be possible to do so.

Actively stopping a run also potentially costs you future points if your robot does not crash in the end and continues, so the teams need to actually know their system to make a good judgement in competition situations. I like the idea that this is awarded as it shows a teams' knowledge in the field. Sometimes it also penalizes a team for a wrong call (e.g. our BTT3 I think), which prevents "easy" restarts.

The teams that often crash also have "less" handicap in the form of them not getting the penalty points. But it still requires them to observe their robot and make the decisions, so we could award that.

If we defined some timespan after such a call, where do we draw the line?
5 seconds have to be stopped and monitored as well, and if after 6s the robot crashes, who makes the call if it's still inside the time stop margin?
I think it could cause a lot of discussions onsite.

**Comment by steup** [comment]
This is actually a hard topic. I like Marco's argument of awarding teams' knowledge of their robot. However, it is also difficult to detect if the call was in time. I think we should aim for a technical solution in the long run. Something like a remote emergency stop via refbox, which then acts as stop or restart and stops the robot.  A major collision is then only avoided if the robot follows the emergency stop command. This is also very much in line with our scenario.

**Comment by Mathemalsky** [comment]
>[...] I think we should aim for a technical solution in the long run. Something like a remote emergency stop via refbox, which then acts as stop or restart and stops the robot. [...]

This also simplify the referees' work because they do not need to keep track of the time span between call and collision. Moreover such a feature would open new rooms for future challenges (e. g. with multiple robot interaction).

**Comment by leanderb** [comment]
We can solve several problems at once by replacing a restart call with pressing a remote stop button. All error prone discussion about timing of the restart call would be eliminated. This also supports the idea of awarding teams knowledge about their robot.
Currently the atwork commander is not really used, so stopping the robot via atwork commander seems not realistic. 

A fallback with a stop button installed at the robot shall also be possible.

**Comment by leanderb** [comment]
TC meeting:
Tactical call of a restart is allowed.
