### ISSUE TITLE
Alternative for the coneyor belt

### ISSUE THREAD

**Issue by frederikhegger** [robocup-at-work/rulebook#6]
https://www.flikto.de/products/openbuilds-v-slot-linearfuhrungen-kit-1000mm-schwarz-1

**Comment by asadnorouzi** [comment]
@deebuls why is it reopened? I don’t think we’re discussing to add any new element to the competition.

**Comment by steup** [comment]
Nothing available as far as I known. If you have something in mind tell us @deebuls.

**Comment by deebuls** [comment]
The idea is to  use not a conveyor belt but a linear actuator. Linear actuator has advantages that we can control speed easily available and we can move objects repeatedly like rotating table .

Some examples:
https://www.youtube.com/watch?v=1PDzEpyDN78
or opensource ones:
https://www.youtube.com/watch?v=tHn-gffborc&list=PLDeI80MYQtbqZahZvCIcOPhE0wO3RirvY


This is a good place where we can ask igus to sponsor us or we can ask robocup federation for funds for creating this challenge. @SebastianZug ?

i personally like the igus option of funding us with sponsoring the equipment and naming the challenge after the company they get marketing advantage.

**Comment by asadnorouzi** [comment]
@deebuls We could request for funding from the Federation. Although, the deadline for next year has already lapsed! However, you should think of the transportation costs as well. Moreover, this would be a new challenge in the arena. Why are we adding a new challenge while we already have enough complications in the arena? Teams are still improving with RTT, PPT, and Shelf. So, I don’t think it’s the right time for it now. We could add it to our roadmap discussion.

**Comment by deebuls** [comment]
@asadnorouzi I agree. 
I will reassign this issue to 2020. 

But can we someone take an action point of talking to igus for sponsorship or finding funding for buying the hardware.
@SebastianZug

**Comment by SebastianZug** [comment]
RTT covers the challenges of "moving targets" already. Hence, I don't see a need to reactivate the conveyor belt. 
@deebuls ... or do you have a completely different idea in mind?
