### ISSUE TITLE
Video Referee / Infrastructure

### ISSUE THREAD

**Issue by marcomasa** [robocup-at-work/rulebook#60]
The league always had some kind of livestream and private camera recordings that were sometimes reviewed when discussing "controversial" situations during the competitions.

The football leagues have a camera rack above their playfield that is used during the competition. If our arena design would also include a top-down view from some height (3 - 5m ?) in form of a camera on a rack around the arena we could profit in multiple ways:
- more interesting livestream for online viewers / monitors
- "official" video material when reviewing situations
- potential automated collision detection?

If we actually get a rack we could also include a visual system connected to the refbox that does some form of basic color codes to indicate the arena state (red = idle, yellow = active, green = competion .... or smth like this)

However, this is a lot of workload for the (local) OC and TC to maintain and operate.
Also, we'd need to organize the material (rack?, cams, lights, computers). Could maybe rent some (festival tech).

The extent of which this can be implemented however obviously still needs to be discussed.
Depends on the encouragement of all committee members to be successful, I think.

**Comment by woutzen** [comment]
A top-down camera as a live stream including a color-coded arena state for visitors is a good idea. But I don't think it is helpful for the referees and causes much more overhead.

The detection of large collisions, where workstations or walls were obviously moved is possible without a camera, touching of workstations/walls and crossing of virtual walls (which are not exactly under the camera in the middle of the arena) can not be clearly detected on such a video and would in quite a few cases probably cause even more discussions.

**Comment by marcomasa** [comment]
We could use more than one camera to cover multiple views.
If we make the effort for organizing a rack, I would even suggest putting 1 top-down and 1 on each side.
I think we had a rack standing on 2.5m poles in 2017 German Open. Doesn't have to be ceiling-mounted that way, and would serve as mounting points for the LED strips as well.

The problem of the effort remains nonetheless.

**Comment by steup** [comment]
A video recording infrastructure like the rack in 2017 would be very beneficial for the league. However, I seriously doubt we can get one from the organizers of any competition. If we want to use something like that, we need to organize, maintain and transport it ourself.

The hardware would also serve more research purposes, so maybe we can ask the federation for funding.

**Comment by marcomasa** [comment]
TC Meeting:

# Regarding the Competition / Streaming
- 4 Cameras  (1 in each arena corner) on poles
- All cameras connected to one PC with OBS (Live Streaming)
- OBS Record function (with sound?) --> VAR

# Optional Tech Rider entry for the video surveillance system
- 1 PC with 4 USB3.0 ports OR 1 USB3.0 Port and an USB3.0 4Port Hub
- 1x Monitor, Mouse, Keyboard, Cables for the PC
- 4 speaker stands as poles (e.g. 2x [this](https://www.thomann.de/de/fun_generation_speaker_stand_pair.htm))
- 4 USB 3.0 Full HD Webcams (e.g. [Logitech BRIO USB 3.0](https://www.mindfactory.de/product_info.php/Logitech-BRIO-Webcam-USB-3-0_1141524.html) )
- 4x active USB extension 10m (e.g. [this](https://www.amazon.de/CSL-Repeaterkabel-Verl%C3%A4ngerungskabel-Verl%C3%A4ngerung-Verst%C3%A4rker/dp/B09R5RB6R3/ref=sr_1_8?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3C9BQZBXPMT4F&keywords=usb+verl%C3%A4ngerung+aktiv&qid=1676300720&sprefix=usb+verl%C3%A4ngerung+aktiv%2Caps%2C111&sr=8-8) )

# Its important that we use USB3.0 standard, as USB2 only allows 2 cameras streaming full hd!
