### ISSUE TITLE
Touching a acontainer, object, decoy considered as deduction or minor collision while placining process?

### ISSUE THREAD

**Issue by AlcatrAAz** [robocup-at-work/rulebook#68]
In sections 5.1.3 (and 5.1.2) a collision is considered as an place deduction and later as a minor collision.

It should be considered as only one? And it should be equivalent to the grasping process. Both should be minor collision or introduction to a grasping deduction?

+

What happens if an grasping/placing process was successful and while the process a minor collision happened. Do you get still the points for successful grasping/placement or does minor collision set these points to zero? Should be written in Rulebook.

**Comment by leanderb** [comment]
TC meeting:
- introduce "reduced manipulation points" (former placement deduction) -> update 6.4 to fixed points
- remove minor collision from grasping and placing process
- update 6.5 minor collision
- update table 6.1
- rework and clarify section 5.1.3
