### ISSUE TITLE
Reduce radius of the rotating table

### ISSUE THREAD

**Issue by frederikhegger** [robocup-at-work/rulebook#7]
maybe to something like 50cm

**Comment by asadnorouzi** [comment]
I would suggest to define a range rather than an exact value.

**Comment by steup** [comment]
Eases Transportation, but complicates construction. I would suggest to postpone the change unless a working prototype of a new table is constructed.

**Comment by asadnorouzi** [comment]
@steup Shall we define a min/max range for the radius? This makes it easier for the organizer to prepare it. What do you think?

**Comment by deebuls** [comment]
@asadnorouzi agree. 
Can anyone also look into a standard easy to reproduce, with minimum moving parts electronic design,
With components available in all the continents.
