### ISSUE TITLE
Clarification of the point deduction for human interaction

### ISSUE THREAD

**Issue by lumb3rjack** [robocup-at-work/rulebook#70]
Due to the wording, "Human interaction during the run", it seems that no matter how many times the human interaction occurs, points are only deducted once. is this correct? In any case, this should be clarified in the list under "6.4 Penalties" and in the table "6.1 Scoring in the instances of the RoboCup@Work 2023 competition" under "6.7 Ranking". 

My recommendation would be to use the keyword "once" here.

**Comment by leanderb** [comment]
I think we (the TC) mean -100 points for each human interaction

**Comment by leanderb** [comment]
see PR #77
