### ISSUE TITLE
Manipulation Deduction Explanation seems wrong

### ISSUE THREAD

**Issue by lumb3rjack** [robocup-at-work/rulebook#71]
In the list in paragraph "6.4 Penalties", "Manipulation Deduction" is assigned a penalty of "fixed 50 points (in any Manipulation scenarios)". No minus is given here, as in all other items of the list. If this was unique I would assume an error, however in the same paragraph there is an explanation that says "The Manipulation Deduction is a fixed point **reward** (50) if one or more deductions happen during a grasping or placing process. (...)" I still assume that a fixed **penalty** of 50 is actually meant here. Also, if in the table "6.1: Scoring in the instances of the RoboCup@Work 2023 competition." the minus is also missing. I ask you to correct this or explain what you mean.

If you implement my [other suggestion](https://github.com/robocup-at-work/rulebook/issues/70#issue-1737151235), I would also suggest not to use the keyword "fixed" but rather "once".

**Comment by leanderb** [comment]
combine with #76

**Comment by leanderb** [comment]
see PR #77
