### ISSUE TITLE
Maximum height for decoys

### ISSUE THREAD

**Issue by woutzen** [robocup-at-work/rulebook#79]
It would be good to have a maximum height for decoys to avoid hardware destruction

**Comment by woutzen** [comment]
Maybe basic properties of decoys could be defined: max and min weight, size

**Comment by marcomasa** [comment]
TC Meeting 8.3.2024:

We agree to limit the maximum height of decoy objects to 10cm. 
This should allow most teams to scan safely but they still have to be careful while grasping.

**Comment by steup** [comment]
Waiting for approval of TC
