### ISSUE TITLE
Mention frequencies of WLAN

### ISSUE THREAD

**Issue by svenschneider** [robocup-at-work/rulebook#8]
The rulebook specifies that the WLAN will be "dual band", but does not mention the concrete frequencies (probably 2.4 GHz and 5 GHz).

**Comment by asadnorouzi** [comment]
@svenschneider Any specific reason for this?

**Comment by svenschneider** [comment]
Sorry, no idea what that was about.

**Comment by steup** [comment]
Impossible as defined through the venue and federation. Maybe we can switch to 5Ghz only, because this was the case for the last years

**Comment by asadnorouzi** [comment]
This’s out of our control. So, no point to discuss this further.
