### ISSUE TITLE
Open Source Award

### ISSUE THREAD

**Issue by woutzen** [robocup-at-work/rulebook#82]
An Open Source Award / Open Hardware Award could be assigned to motivate teams to share their development state.

**Comment by marcomasa** [comment]
TC Meeting 8.3.2024:

We agree on a technical challenge that teams can participate onsite.
Teams hand in their links / resources and ALL OTHER TEAMS rate this material.
The TC is not involved here, as we want to leave it up to the teams which Repository is "the best".

Each Team can internally decide on their rating, but must communicate the result to the TC
via their Teamlead.

Voting could be:
- Each team gets 3 votes. Team with the most total votes wins.
- Each team must give 1-5 Points to each participating team. Team with the most points wins.

**Comment by woutzen** [comment]
Waiting for approval of TC
