### ISSUE TITLE
Provision of objects and check of arena configuration

### ISSUE THREAD

**Issue by steup** [robocup-at-work/rulebook#84]
Teams are responsible for providing any special objects they need (e.g., april tagged cubes) in appropriate numbers. If an object of a task cannot be replaced because of a missing april tagged cube, the object should be left out. If objects are present multiple times, the referees should decide on the cube to be left out.

The team leader / Team ref are responsible to check if the arena is complete and correct. Any error not detected before the run are taken as is. The error cannot be fixed for other teams for the same tests.

**Comment by marcomasa** [comment]
TC Meeting 8.3.2024:

Add comment in the simplification section:

"Teams that want to use this option are advised to bring two complete sets of rule compliant cubes with them to ensure that all objects from the regular tasks can be replaced. If a cube is missing, .. its bad luck for them idk .. "

**Comment by marcomasa** [comment]
Also add a comment in the participation section that says

"Teams should bring one complete set of objects to a competition to ensure that we have enough objects onsite for all types of tasks"

**Comment by steup** [comment]
Waiting for approval of TC

**Comment by marcomasa** [comment]
Object provision is covered by the commit.

Arena State is a responsibility of the Refs. 
The initial state is gonna be validated by the TC to ensure that the Task itself is ok by rulebook definition.
