### ISSUE TITLE
Arbitrary Surfaces and April tagged cubes

### ISSUE THREAD

**Issue by steup** [robocup-at-work/rulebook#86]
Arbitrary Surfaces should be removed for april tagged cubes, since the challenge of detection is missing. The nly challenge is height detection and grass avoidance, which can both be solved by hardcoding height offsets in grasping the cubes.

**Comment by marcomasa** [comment]
TC Meeting 8.3.2024:

We remove arbitrary surfaces (also physically) (including the bonus points) for tasks with april tagged cubes.
Add to simplification section.
