### ISSUE TITLE
On-cup team leader meeting organization

### ISSUE THREAD

**Issue by woutzen** [robocup-at-work/rulebook#87]
There are regular team leader meeting during the world cup to discuss current issues. These are usually organized and moderated by Christoph Steup, but this is not defined in the rulebook. We should define, who is responsible for the organization and execution of those meetings.

**Comment by marcomasa** [comment]
TC Meeting 8.3.2024:

We will add some comments to the general onsite schedule with default slots.

TC / EC can cancel the slots if they dont need them, but the general plan is to have them e.g. twice a day.

**Comment by marcomasa** [comment]
Fixed in [this commit](https://github.com/robocup-at-work/rulebook/commit/e78ce6588b49bd42ad46afea7ef0d084c9cbf223)
