### ISSUE TITLE
Manipulation Deduction at scanning/testing the object??

### ISSUE THREAD

**Issue by AlcatrAAz** [robocup-at-work/rulebook#90]
Is it a manipulation deduction if you pick a wrong object and then scan it with your camera. This method is written in the rulebook to avoid a wrong object manipulation.
+
Is it a manipulation deduction if you pick a wrong object and then check with your gripper information if the size is the correct and measure the weight of the object.

-------------

At the moment it is a Manipulation Deduction as you touch a wrong object while the grasping process.
Should this be changed to No Manipulation Deduction if the robot does it in a controlled way. For example place the object again on the WS if it was the wrong object after scanning, gripper info, weight etc...??

**Comment by marcomasa** [comment]
I think this is covered with the manipulation zone and when penalties are applied. We even have such an inspection example somewhere.
